"""Add subcounty, ward, latitude, longitude to ResourceCenter

Revision ID: e077e496071c
Revises: 
Create Date: 2026-09-19 09:09:24.760370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e077e496071c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_centers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcounty', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resource_centers', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('ward')
        batch_op.drop_column('subcounty')

    # ### end Alembic commands ###
